### ISSUE TITLE
changeNoteTuning strange behavior

### ISSUE THREAD

**Issue by ghost** [duggan/midiutil#1]
I am trying to write a microtone to a track, and the same pitch (non-micorotnal) to another track, but then both tracks have only the microtonal pitch:

    MyMIDI = MIDIFile(2)
    MyMIDI.addTempo(0, 0,60) 
    MyMIDI.addTrackName(0, 0,"Hello world!")
    # set 60 -> 69
    tunings = [(60, 440)]
    # write this tuning to the first track
    MyMIDI.changeNoteTuning(0, tunings)

    MyMIDI.addNote(0, 0, 60, 0, .5, 127)
    MyMIDI.addNote(1, 0, 60, 0, .5, 127)

    binfile = open("/tmp/util.midi", 'wb')
    MyMIDI.writeFile(binfile)
    binfile.close()

Now i have two tracks both with an A (69). Why is this happening?

**Comment by duggan** [comment]
Didn't realize issues were open on this. For folks arriving here from Google, https://github.com/MarkCWirt/MIDIUtil seems to be the current canonical source maintained by the author.
